apps/listings/urls.py
# apps/listings/urls.py

# Django modules
from django.urls import path

# Locals
from apps.listings import views  

# Appname
app_name = 'listings'

# Urls
urlpatterns = [
    path('listing-list', views.listing_list, name='listing_list'),
    path('listing-detail/<int:listing_id>/', views.listing_detail, name='listing_detail'),
]

apps/pages/urls.py
# apps/pages/urls.py

# Django modules
from django.urls import path

# Locals
from apps.pages import views  

# Appname
app_name = 'pages'

# Urls
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

realestate/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Locals

urlpatterns = [
    # Pages
    path('', include('apps.pages.urls', namespace='pages')),

    # Listings
    path('', include('apps.listings.urls', namespace='listings')),

    # Admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/listings/models.py
# apps/listings/models.py

# Django modules
from django.db import models
from datetime import datetime

# Locals
from apps.realtors.models import Realtor

# Create your models here.

class Listing(models.Model):

	realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
	title = models.CharField(max_length=200)
	address = models.CharField(max_length=200)
	city = models.CharField(max_length=200)
	state = models.CharField(max_length=200)
	zipcode = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	price = models.IntegerField()
	bedrooms = models.IntegerField()
	bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
	garage = models.IntegerField(default=0)
	sqft = models.IntegerField()
	lot_size = models.DecimalField(max_digits=5, decimal_places=1)
	photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
	photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
	is_published = models.BooleanField(default=True)
	list_date = models.DateTimeField(default=datetime.now, blank=True)

	def __str__(self):
		return self.title  

apps/realtors/models.py
# apps/listings/models.py

# Django modules
from django.db import models
from datetime import datetime

# Create your models here.

class Realtor(models.Model):

	name = models.CharField(max_length=200)
	photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
	description = models.TextField(blank=True)
	phone = models.CharField(max_length=20)
	email = models.CharField(max_length=30)
	is_mvp = models.BooleanField(default=False)
	hire_date = models.DateTimeField(default=datetime.now, blank=True)

	def __str__(self):
		return self.name  

apps/listings/views.py
# apps/listings/views.py

# Django modules
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# locals
from apps.listings.models import Listing

# Create your views here.

def listing_list(request):
	# listings = Listing.objects.all()
	listings = Listing.objects.order_by('-list_date').filter(is_published=True)

	# Get 3 listings objects per page
	paginator = Paginator(listings, 3)
	# Passing the url parameter 'page' to the GET method
	page = request.GET.get('page')
	# Get the page
	page_listings = paginator.get_page(page)

	context = {
		# 'listings':listings,
		'listings':page_listings
	}
	return render(request, 'listings/listing_list.html', context)

def listing_detail(request, listing_id):
	listing = get_object_or_404 (Listing, pk=listing_id)
	print(listing)
	context = {'listing':listing}
	return render(request, 'listings/listing_detail.html', context)

apps/pages/views.py
# apps/pages/views.py

# Django modules
from django.shortcuts import render

# Locals
from apps.listings.models import Listing
from apps.realtors.models import Realtor

# Create your views here.

def home(request):
	listings = Listing.objects.order_by('-list_date').filter(is_published=True)[:3]
	context = {'listings':listings}
	return render(request, 'pages/index.html', context)

def about(request):
	# Get all the realtors
	realtors = Realtor.objects.order_by('-hire_date')

	# Get MVP
	mvp_realtors = Realtor.objects.all().filter(is_mvp=True)

	context = {
		'realtors':realtors,
		'mvp_realtors':mvp_realtors
	}

	return render(request, 'pages/about.html', context)

apps/realtors/views.py
from django.shortcuts import render

# Create your views here.

apps/listings/templates/listings/listing_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %}Detail{% endblock title %}


    {% block content %}
    
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">{{listing.title|title}}</h1>
                    <p class="lead">
                        <i class="fas fa-map-marker"></i> {{listing.city}} {{listing.state}} {{listing.zipcode}}
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'listings:listing_list' %}">Listings</a>
                    </li>
                    <li class="breadcrumb-item active">{{listing.title|title}}</li>
                </ol>
            </nav>
        </div>
    </section>
    <!-- Listing -->
    <section id="listing" class="py-4">
        <div class="container">
            <a href="{% url 'listings:listing_list' %}" class="btn btn-light mb-4">Back To Listings</a>
            <div class="row">
                <div class="col-md-9">
                    <!-- Home Main Image -->
                    <img src="{{listing.photo_main.url}}" alt="" class="img-main img-fluid mb-3">
                    <!-- Thumbnails -->
                    <div class="row mb-5 thumbs">
                    	{% if listing.photo_1 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_1.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_1.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    	{% if listing.photo_2 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_2.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_2.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    	{% if listing.photo_3 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_3.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_3.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    	{% if listing.photo_4 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_4.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_4.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    	{% if listing.photo_5 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_5.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_5.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    	{% if listing.photo_6 %}
                        <div class="col-md-2">
                            <a href="{{listing.photo_6.url}}" data-lightbox="home-images">
                            <img src="{{listing.photo_6.url}}" alt="" class="img-fluid">
                            </a>
                        </div>
                        {% endif %}
                    </div>
                    <!-- Fields -->
                    <div class="row mb-5 fields">
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-money-bill-alt"></i> Asking Price:
                                    <span class="float-right">${{listing.price|intcomma}}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bed"></i> Bedrooms:
                                    <span class="float-right">{{listing.bedrooms}}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bath"></i> Bathrooms:{{listing.bathrooms}}
                                    <span class="float-right">2</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-car"></i> Garage:
                                    <span class="float-right">{{listing.garage}}
                                    </span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-th-large"></i> Square Feet:
                                    <span class="float-right">{{listing.sqft}}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-square"></i> Lot Size:
                                    <span class="float-right">{{listing.lot_size}} Acres
                                    </span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-calendar"></i> Listing Date:
                                    <span class="float-right">{{listing.list_date}}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-bed"></i> Realtor:
                                    <span class="float-right">{{listing.realtor|title}}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Description -->
                    <div class="row mb-5">
                        <div class="col-md-12">
                            {{listing.description}}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card mb-3">
                        <img class="card-img-top" src="{{listing.realtor.photo.url}}" alt="Seller of the month">
                        <div class="card-body">
                            <h5 class="card-title">Property Realtor</h5>
                            <h6 class="text-secondary">{{listing.realtor|title}}</h6>
                        </div>
                    </div>
                    <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
                </div>
            </div>
        </div>
    </section>
    <!-- Inquiry Modal -->
    <div class="modal fade" id="inquiryModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
                    <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="property_name" class="col-form-label">Property:</label>
                            <input type="text" name="listing" class="form-control" value="45 Drivewood Cirlce" disabled>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-form-label">Email:</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="phone" class="col-form-label">Phone:</label>
                            <input type="text" name="phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="message" class="col-form-label">Message:</label>
                            <textarea name="message" class="form-control"></textarea>
                        </div>
                        <hr>
                        <input type="submit" value="Send" class="btn btn-block btn-secondary">
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock content %}

apps/listings/templates/listings/listing_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %}Home{% endblock title %}


    {% block content %}

    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Browse Our Properties</h1>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                        <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> Browse Listings</li>
                </ol>
            </nav>
        </div>
    </section>
    <!-- Listings -->
    <section id="listings" class="py-4">
        <div class="container">
            <div class="row">
                {% if listings %}
                {% for listing in listings %}
                <!-- Listing Card -->
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{listing.photo_main.url}}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                                <span class="badge badge-secondary text-white">${{ listing.price | intcomma }}</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                                <h4 class="text-primary">{{listing.title|title}}</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i>{{listing.address|title}}
                                </p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}
                                </div>
                                <div class="col-6">
                                    <i class="fas fa-car"></i> Garage: {{listing.garage}}
                                </div>
                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}
                                </div>
                                <div class="col-6">
                                    <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}
                                </div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-user"></i> {{listing.realtor|title}}
                                </div>
                            </div>
                            <div class="row text-secondary pb-2">
                                <div class="col-6">
                                    <i class="fas fa-clock"></i>{{listing.list_date|timesince}} ago
                                </div>
                            </div>
                            <hr>
                            <a href="{% url 'listings:listing_detail' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                    </div>
                </div>
                <!-- Listing Card End-->
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                    <p>No listings available.</p>
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Pagination -->
                    {% if listings.has_other_pages %}
                    <ul class="pagination">

                        {% if listings.has_previous %}
                        <li class="page-item">
                            <a 
                                class="page-link" 
                                href="?page={{listings.preveous_page_number}}">
                                &laquo;
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a 
                                class="page-link" 
                                href="#">
                                &laquo;
                            </a>
                        </li>                        
                        {% endif %}

                        <!-- Looping the page -->
                        {% for i in listings.paginator.page_range %}
                            {% if listings.number == i %}
                                <!-- Showing the active link -->
                                <li class="page-item active">
                                    <a href="" class="page-link">{{i}}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        <!-- Showing the Next -->
                        {% if listings.has_next %}
                        <li class="page-item">
                            <a 
                                class="page-link" 
                                href="?page={{listings.next_page_number}}">
                                &raquo;
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a 
                                class="page-link" 
                                href="#">
                                &raquo;
                            </a>
                        </li>                        
                        {% endif %}
                    {% endif %}
                    <!-- End Pagination -->
                </div>
            </div>
        </div>
    </section>

    {% endblock content %}

apps/pages/templates/pages/about.html
<!-- apps/templates/pages/about.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">About BT Real Estate</h1>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'pages:home' %}">
                        <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> About</li>
                </ol>
            </nav>
        </div>
    </section>
    <section id="about" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h2>We Search For The Perfect Home</h2>
                    <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
                    <img src="{% static 'assets/img/about.jpg' %}" alt="">
                    <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis esse officia repudiandae ad saepe ex, amet
                        neque quod accusamus rem quia magnam magni dolorum facilis ullam minima perferendis? Exercitationem at quaerat
                        commodi id libero eveniet harum perferendis laborum molestias quia.
                    </p>
                </div>

                <!-- Seller of the month -->
                {% if mvp_realtors %}
                {% for mvp_realtor in mvp_realtors %}
                <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{{mvp_realtor.photo.url}}" alt="Seller of the month">
                        <div class="card-body">
                            <h5 class="card-title">Seller Of The Month</h5>
                            <h6 class="text-secondary">{{mvp_realtor.name|title}}</h6>
                            <p class="card-text">
                                {{mvp_realtor.description}}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                    <p>No Best Seller available.</p>
                </div>
                {% endif %}
                <!-- Seller of the month -->
            </div>
        </div>
    </section>
    <!-- Work -->
    <section id="work" class="bg-dark text-white text-center">
        <h2 class="display-4">We Work For You</h2>
        <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
        <hr>
        <a href="listings.html" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
    </section>
    <!-- Team -->
    <section id="team" class="py-5">
        <div class="container">
            <h2 class="text-center">Our Team</h2>
            <div class="row text-center">
                {% if realtors %}
                {% for realtor in realtors %}
                <!-- Team Card -->
                <div class="col-md-4">
                    <img src="{{realtor.photo.url}}" alt="" class="rounded-circle mb-3">
                    <h4>{{realtor.name|title}}</h4>
                    {% if realtor.is_mvp == True %}
                    <p class="text-success">
                        <i class="fas fa-award text-success mb-3"></i> Realtor <span style="color:#080808;">(Best Seller)</span>
                    </p>
                    {% else %}
                    <p class="text-success">
                        <i class="fas fa-award text-success mb-3"></i> Realtor
                    </p>                    
                    {% endif %}
                    <hr>
                    <p>
                        <i class="fas fa-phone"></i> {{realtor.phone}}
                    </p>
                    <p>
                        <i class="fas fa-envelope-open"></i> {{realtor.email}}
                    </p>
                </div>
                <!-- Team Card END -->
                {% endfor %}
                {% else %}
                <div class="col-md-12">
                    <p>No Realtors available.</p>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>RealEsate Listings | {% block title %}{{block.super}}{% endblock title %}</title>
	{% include 'inc/head.html'%}
</head>
<body>

	{% include 'inc/topbar.html' %}
	{% include 'inc/navbar.html' %}
	
	{% block content %}
	{% endblock content %}

    <!-- Footer -->
    {% include 'inc/footer.html' %}
    <!-- Scripts -->
    {% include 'inc/scripts.html' %}

</body>
</html>

templates/inc/footer.html
{% load static %}

    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
        Copyright &copy;
        <span class="year"></span> BT Real Estate
    </footer>

templates/inc/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.min.css' %}">

templates/inc/navbar.html
{% load static %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'pages:home' %}">
            <img src="{% static 'assets/img/logo.png' %}" class="logo" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item active mr-3">
                        <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="{% url 'listings:listing_list' %}">Featured Listings</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="register.html">
                        <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="login.html">
                        <i class="fas fa-sign-in-alt"></i>
                        Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

templates/inc/scripts.html
{% load static %}
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

templates/inc/topbar.html
{% load static %}

    <section id="top-bar" class="p-3">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <i class="fas fa-phone"></i> (617)-555-5555
                </div>
                <div class="col-md-4">
                    <i class="fas fa-envelope-open"></i> contact@btrealestate.co
                </div>
                <div class="col-md-4">
                    <div class="social text-right">
                        <a href="#">
                        <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                        <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#">
                        <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="#">
                        <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#">
                        <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>